
server:
  port: 8083

spring:
  application:
    name: voyage-common

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080

